### PR TITLE
Add missing dependency: fiona v.1.9.6

### PR DESCRIPTION
**Pull request by Mengesh**

### CODE REVIEW

**Comment by Mengesh** [comment]
Actually openquake version should be fixed to 3.14.0

**Comment by volkanozsarac** [comment]
Openquake installation via pip is very troublesome, it is better to follow the instructions I wrote. For now it works for oq 3.16.7. I need to make comprehensive changes for newer versions.

**Comment by Mengesh** [comment]
Thank you for the prompt reply!  And sorry for pull request spamming.  I just saw the rest of the instructions.  I'm wondering what's the reason of not putting the dependencies from `txt` files to `setup.cfg`, `openquake` one in particular? I just managed to install and run `EzGM` with `python 3.12.3` and `openquake 3.16.7`.

**Comment by volkanozsarac** [comment]
I am not sure why but OpenQuake developers do not recommend installing it using pypi. I guess some packages are not correctly installed when we directly use pypi. That is why I decided to use requirements.txt in the end, it installs correct oq dependencies. And to be honest, I have not worked on the code for a while. If the way you installed works, we can change setup.cfg!

**Comment by volkanozsarac** [comment]
> So it actually does not work with python 3.12 but 3.11.9. I successfully run [Example1.py](https://github.com/volkanozsarac/EzGM/blob/master/Examples/demo%20scripts/Example1.py) from demo scripts with a slight change - example C) fails with chrome browser but it works with firefox. I'll make a pull request with an updated `setup.cfg`.

I believe, download should work with chrome in the latest version, at least, it was working in windows OS.

**Pull request closed without merging**
